package main

import (
	"context"
	"embed"
	"encoding/json"
	"flag"
	"html/template"
	"io/fs"
	stdlog "log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"pennywise/config"
	"pennywise/db"
	"pennywise/http/router"
	"pennywise/log"
	"syscall"
	"time"

	"github.com/olivere/vite"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

//go:embed all:web/dist
var dist embed.FS

//go:embed all:web/public
var public embed.FS

func main() {
	var (
		isDev = flag.Bool("dev", false, "run in development mode")
	)
	flag.Parse()

	err := config.InitConfig()
	if err != nil {
		stdlog.Fatalf("Failed to parse config: %v", err)
	}

	// Initialize logger
	log.Init(config.Config.LogLevel, config.Config.LogFormat)

	err = db.InitDB()
	if err != nil {
		stdlog.Fatalf("Failed to connect to database: %v", err)
	}

	db.RunMigrations()

	mux := http.NewServeMux()
	setupVite(*isDev, mux)
	router.InitRouter(mux)

	// Create HTTP server
	addr := ":3333"
	srv := &http.Server{
		Addr:    addr,
		Handler: h2c.NewHandler(mux, &http2.Server{}),
	}

	// Channel to listen for shutdown signals
	shutdown := make(chan os.Signal, 1)
	signal.Notify(shutdown, os.Interrupt, syscall.SIGTERM)

	// Start server in a goroutine
	serverErrors := make(chan error, 1)
	go func() {
		log.Info("Starting server", "addr", addr, "dev_mode", *isDev)
		serverErrors <- srv.ListenAndServe()
	}()

	// Wait for shutdown signal or server error
	select {
	case err := <-serverErrors:
		if err != nil && err != http.ErrServerClosed {
			stdlog.Fatalf("Server error: %v", err)
		}
	case sig := <-shutdown:
		log.Info("Received shutdown signal", "signal", sig)

		// Create context with timeout for graceful shutdown
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()

		// Attempt graceful shutdown
		if err := srv.Shutdown(ctx); err != nil {
			log.Error("Failed to gracefully shutdown server", "error", err)
			if err := srv.Close(); err != nil {
				log.Error("Failed to force close server", "error", err)
			}
		} else {
			log.Info("Server shutdown gracefully")
		}

		// Close database connections
		db.CloseDB()
	}
}

func setupVite(isDev bool, mux *http.ServeMux) {
	var appFS, publicFS fs.FS
	if isDev {
		appFS = os.DirFS("./web")
		publicFS = os.DirFS("./web/public")
	} else {
		distFS, err := fs.Sub(dist, "web/dist")
		if err != nil {
			stdlog.Fatalf("creating sub-filesystem for 'dist' directory: %v", err)
		}
		appFS = distFS

		publicSub, err := fs.Sub(public, "web/public")
		if err != nil {
			stdlog.Fatalf("creating sub-filesystem for 'public' directory: %v", err)
		}
		publicFS = publicSub
	}

	// Handle requests for Vite-managed assets.
	mux.Handle("/assets/", http.FileServerFS(appFS))

	// Register the endpoints that get served by the frontend.
	fePaths := []string{
		"/{$}",
		"/index.html",
		"/about",
		"/auth/register",
		"/auth/login",
		"/dashboard",
		"/group/{id}",
	}
	feHandler := FrontendHandler(isDev, appFS, publicFS, fePaths...)
	for _, page := range fePaths {
		mux.HandleFunc(page, feHandler)
	}

	// Catch-all for static files (favicons, manifest, etc.) from dist
	mux.Handle("/{path...}", http.FileServerFS(appFS))
}

// FrontendConfig holds configuration values passed to the frontend
type FrontendConfig struct {
	OIDCEnabled         bool `json:"oidcEnabled"`
	RegistrationEnabled bool `json:"registrationEnabled"`
}

func FrontendHandler(isDev bool, appFS, publicFS fs.FS, paths ...string) http.HandlerFunc {
	viteConfig := vite.Config{
		FS:           appFS,
		IsDev:        isDev,
		ViteTemplate: vite.React,
	}
	if isDev {
		viteConfig.ViteURL = "http://localhost:5173"
	}

	// Build frontend config and serialize to JSON
	feConfig := FrontendConfig{
		OIDCEnabled:         config.Config.OIDCEnabled(),
		RegistrationEnabled: config.Config.RegistrationEnabled,
	}
	configJSON, err := json.Marshal(feConfig)
	if err != nil {
		stdlog.Fatalf("Failed to marshal frontend config: %v", err)
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		for _, path := range paths {
			if r.Pattern == path {
				viteFragment, err := vite.HTMLFragment(viteConfig)
				if err != nil {
					stdlog.Fatalf("Error instantiating vite fragment: %v", err)
					http.Error(w, "Error instantiating vite fragment", http.StatusInternalServerError)
					return
				}

				tmpl, err := template.New("index").Parse(indexTmpl)
				if err != nil {
					stdlog.Fatalf("Error parsing template: %v", err)
					http.Error(w, "Error parsing template", http.StatusInternalServerError)
					return
				}

				if err = tmpl.Execute(w, map[string]any{
					"Title":      "Homepage",
					"Vite":       viteFragment,
					"ConfigJSON": template.JS(configJSON),
				}); err != nil {
					stdlog.Fatalf("Error executing template: %v", err)
					http.Error(w, "Error executing template", http.StatusInternalServerError)
					return
				}
				return
			}
		}

		// Serve the public files generated by Vite. By default, these files are
		// referenced in the DOM with a root-relative URL format (e.g. '/file.ext').
		http.ServeFileFS(w, r, publicFS, filepath.Base(r.URL.Path))
	})
}

var indexTmpl = `<!doctype html>
<html lang="en" class="h-full scroll-smooth">
  <head>
    <meta charset="UTF-8" />
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon-180x180.png">
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/favicon-192x192.png">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/favicon-144x144.png">
    <meta name="msapplication-config" content="/browserconfig.xml">
    <link rel="manifest" href="/manifest.webmanifest">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ .Title }}</title>
    {{ .Vite.Tags }}
    <script>window.__PENNYWISE_CONFIG__ = {{ .ConfigJSON }};</script>
  </head>
  <body class="min-h-screen antialiased">
    <div id="root"></div>
  </body>
</html>
`

//go:generate sqlc generate
//go:generate buf generate
