// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const getGroupActivityCount = `-- name: GetGroupActivityCount :one
SELECT COUNT(*) AS total FROM (
  SELECT e.id FROM expenses e
  INNER JOIN expense_payers p ON p.expense_id = e.id
  INNER JOIN expense_beneficiaries b ON b.expense_id = e.id
  WHERE e.group_id = ?1
    AND (?2 = '' OR ?2 = 'expense')
    AND (?3 = '' OR e.currency = ?3)
    AND (?4 = '' OR p.user_id = ?4 OR b.user_id = ?4)
  GROUP BY e.id

  UNION ALL

  SELECT t.id FROM transfers t
  WHERE t.group_id = ?1
    AND (?2 = '' OR ?2 = 'transfer')
    AND (?3 = '' OR t.currency = ?3)
    AND (?4 = '' OR t.sender_id = ?4 OR t.receiver_id = ?4)
)
`

type GetGroupActivityCountParams struct {
	GroupID        string
	TypeFilter     interface{}
	CurrencyFilter interface{}
	MemberFilter   interface{}
}

func (q *Queries) GetGroupActivityCount(ctx context.Context, arg GetGroupActivityCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGroupActivityCount,
		arg.GroupID,
		arg.TypeFilter,
		arg.CurrencyFilter,
		arg.MemberFilter,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getGroupActivityPaginated = `-- name: GetGroupActivityPaginated :many
SELECT
  e.id AS id,
  'expense' AS type,
  e.date AS date,
  e.created_at AS created_at,
  e.name AS description,
  e.currency AS currency,
  p.amount AS amount,
  p.user_id AS actor_id,
  u.username AS actor_name,
  CAST(NULL AS TEXT) AS receiver_id,
  CAST(NULL AS TEXT) AS receiver_name,
  json_group_array(b.user_id) AS beneficiaries_ids,
  e.recurring_id AS recurring_id
FROM expenses e
INNER JOIN expense_payers p ON p.expense_id = e.id
INNER JOIN users u ON u.id = p.user_id
INNER JOIN expense_beneficiaries b ON b.expense_id = e.id
WHERE e.group_id = ?2
  AND (?3 = '' OR ?3 = 'expense')
  AND (?4 = '' OR e.currency = ?4)
  AND (?5 = '' OR p.user_id = ?5 OR b.user_id = ?5)
  AND (
    ?6 = '' OR
    e.date < ?6 OR
    (e.date = ?6 AND e.created_at < ?7) OR
    (e.date = ?6 AND e.created_at = ?7 AND e.id < ?8)
  )
GROUP BY e.id

UNION ALL

SELECT
  t.id,
  'transfer' AS type,
  t.date,
  t.created_at,
  'Transfer' AS description,
  t.currency,
  t.amount,
  t.sender_id AS actor_id,
  s.username AS actor_name,
  t.receiver_id,
  r.username AS receiver_name,
  CAST(NULL AS TEXT) AS beneficiaries_ids,
  CAST(NULL AS TEXT) AS recurring_id
FROM transfers t
JOIN users s ON s.id = t.sender_id
JOIN users r ON r.id = t.receiver_id
WHERE t.group_id = ?2
  AND (?3 = '' OR ?3 = 'transfer')
  AND (?4 = '' OR t.currency = ?4)
  AND (?5 = '' OR t.sender_id = ?5 OR t.receiver_id = ?5)
  AND (
    ?6 = '' OR
    t.date < ?6 OR
    (t.date = ?6 AND t.created_at < ?7) OR
    (t.date = ?6 AND t.created_at = ?7 AND t.id < ?8)
  )

ORDER BY date DESC, created_at DESC, id DESC
LIMIT ?1
`

type GetGroupActivityPaginatedParams struct {
	Limit           int64
	GroupID         string
	TypeFilter      interface{}
	CurrencyFilter  interface{}
	MemberFilter    interface{}
	CursorDate      interface{}
	CursorCreatedAt overrides.TextTime
	CursorID        string
}

type GetGroupActivityPaginatedRow struct {
	ID               string
	Type             string
	Date             overrides.TextTime
	CreatedAt        overrides.TextTime
	Description      string
	Currency         string
	Amount           int64
	ActorID          string
	ActorName        string
	ReceiverID       *string
	ReceiverName     *string
	BeneficiariesIds interface{}
	RecurringID      *string
}

func (q *Queries) GetGroupActivityPaginated(ctx context.Context, arg GetGroupActivityPaginatedParams) ([]GetGroupActivityPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupActivityPaginated,
		arg.Limit,
		arg.GroupID,
		arg.TypeFilter,
		arg.CurrencyFilter,
		arg.MemberFilter,
		arg.CursorDate,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupActivityPaginatedRow
	for rows.Next() {
		var i GetGroupActivityPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.CreatedAt,
			&i.Description,
			&i.Currency,
			&i.Amount,
			&i.ActorID,
			&i.ActorName,
			&i.ReceiverID,
			&i.ReceiverName,
			&i.BeneficiariesIds,
			&i.RecurringID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
