// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversions.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const createCurrencyConversion = `-- name: CreateCurrencyConversion :one
INSERT INTO currency_conversions
(
    id,
    created_at,
    group_id,
    from_currency,
    to_currency,
    rate,
    date
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
) RETURNING id, group_id, from_currency, to_currency, rate, created_at, date
`

type CreateCurrencyConversionParams struct {
	ID           string
	CreatedAt    overrides.TextTime
	GroupID      string
	FromCurrency string
	ToCurrency   string
	Rate         float64
	Date         overrides.TextTime
}

func (q *Queries) CreateCurrencyConversion(ctx context.Context, arg CreateCurrencyConversionParams) (CurrencyConversion, error) {
	row := q.db.QueryRowContext(ctx, createCurrencyConversion,
		arg.ID,
		arg.CreatedAt,
		arg.GroupID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Rate,
		arg.Date,
	)
	var i CurrencyConversion
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.CreatedAt,
		&i.Date,
	)
	return i, err
}

const deleteCurrencyConversion = `-- name: DeleteCurrencyConversion :exec
DELETE FROM currency_conversions WHERE id = ?1
`

func (q *Queries) DeleteCurrencyConversion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCurrencyConversion, id)
	return err
}

const getCurrencyConversionById = `-- name: GetCurrencyConversionById :one
SELECT id, group_id, from_currency, to_currency, rate, created_at, date FROM currency_conversions WHERE id = ?1
`

func (q *Queries) GetCurrencyConversionById(ctx context.Context, id string) (CurrencyConversion, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyConversionById, id)
	var i CurrencyConversion
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.CreatedAt,
		&i.Date,
	)
	return i, err
}

const getGroupConversions = `-- name: GetGroupConversions :many
SELECT id, group_id, from_currency, to_currency, rate, created_at, date
FROM currency_conversions
WHERE group_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) GetGroupConversions(ctx context.Context, groupID string) ([]CurrencyConversion, error) {
	rows, err := q.db.QueryContext(ctx, getGroupConversions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrencyConversion
	for rows.Next() {
		var i CurrencyConversion
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Rate,
			&i.CreatedAt,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupConversionsForBalance = `-- name: GetGroupConversionsForBalance :many
SELECT
    id,
    from_currency,
    to_currency,
    rate,
    created_at,
    date
FROM currency_conversions
WHERE group_id = ?1
`

type GetGroupConversionsForBalanceRow struct {
	ID           string
	FromCurrency string
	ToCurrency   string
	Rate         float64
	CreatedAt    overrides.TextTime
	Date         overrides.TextTime
}

func (q *Queries) GetGroupConversionsForBalance(ctx context.Context, groupID string) ([]GetGroupConversionsForBalanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupConversionsForBalance, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupConversionsForBalanceRow
	for rows.Next() {
		var i GetGroupConversionsForBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Rate,
			&i.CreatedAt,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrencyConversion = `-- name: UpdateCurrencyConversion :one
UPDATE currency_conversions
SET
    from_currency = ?1,
    to_currency = ?2,
    rate = ?3,
    date = ?4
WHERE id = ?5
RETURNING id, group_id, from_currency, to_currency, rate, created_at, date
`

type UpdateCurrencyConversionParams struct {
	FromCurrency string
	ToCurrency   string
	Rate         float64
	Date         overrides.TextTime
	ID           string
}

func (q *Queries) UpdateCurrencyConversion(ctx context.Context, arg UpdateCurrencyConversionParams) (CurrencyConversion, error) {
	row := q.db.QueryRowContext(ctx, updateCurrencyConversion,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Rate,
		arg.Date,
		arg.ID,
	)
	var i CurrencyConversion
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.CreatedAt,
		&i.Date,
	)
	return i, err
}
