// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package database

import (
	"context"
	"time"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses
(
    id,
    created_at,
    group_id,
    recurring_id,
    name,
    description,
    currency
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, created_at, group_id, recurring_id, name, description, currency
`

type CreateExpenseParams struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	GroupID     string    `json:"group_id"`
	RecurringID *string   `json:"recurring_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Currency    string    `json:"currency"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ID,
		arg.CreatedAt,
		arg.GroupID,
		arg.RecurringID,
		arg.Name,
		arg.Description,
		arg.Currency,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GroupID,
		&i.RecurringID,
		&i.Name,
		&i.Description,
		&i.Currency,
	)
	return i, err
}

const createExpenseBeneficiary = `-- name: CreateExpenseBeneficiary :one
INSERT INTO expense_beneficiaries
(
    id,
    expense_id,
    user_id
) VALUES (
    ?1, ?2, ?3
) RETURNING id, expense_id, user_id
`

type CreateExpenseBeneficiaryParams struct {
	ID        string `json:"id"`
	ExpenseID string `json:"expense_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) CreateExpenseBeneficiary(ctx context.Context, arg CreateExpenseBeneficiaryParams) (ExpenseBeneficiary, error) {
	row := q.db.QueryRowContext(ctx, createExpenseBeneficiary, arg.ID, arg.ExpenseID, arg.UserID)
	var i ExpenseBeneficiary
	err := row.Scan(&i.ID, &i.ExpenseID, &i.UserID)
	return i, err
}

const createExpensePayer = `-- name: CreateExpensePayer :one
INSERT INTO expense_payers
(
    id,
    expense_id,
    user_id,
    amount
) VALUES (
    ?1, ?2, ?3, ?4
) RETURNING id, expense_id, user_id, amount
`

type CreateExpensePayerParams struct {
	ID        string `json:"id"`
	ExpenseID string `json:"expense_id"`
	UserID    string `json:"user_id"`
	Amount    int64  `json:"amount"`
}

func (q *Queries) CreateExpensePayer(ctx context.Context, arg CreateExpensePayerParams) (ExpensePayer, error) {
	row := q.db.QueryRowContext(ctx, createExpensePayer,
		arg.ID,
		arg.ExpenseID,
		arg.UserID,
		arg.Amount,
	)
	var i ExpensePayer
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
	)
	return i, err
}

const getGroupExpenses = `-- name: GetGroupExpenses :many
SELECT
  e.id, e.created_at, e.group_id, e.recurring_id, e.name, e.description, e.currency,
  p.user_id as payer_id,
  u.username as payer_name,
  p.amount,
  json_group_array(b.user_id) as beneficiaries_ids
FROM
  expenses e
  INNER JOIN expense_payers p ON p.expense_id = e.id
  INNER JOIN users u ON u.id = p.user_id
  INNER JOIN expense_beneficiaries b ON b.expense_id = e.id
WHERE e.group_id = ?1
GROUP BY e.id
`

type GetGroupExpensesRow struct {
	ID               string      `json:"id"`
	CreatedAt        time.Time   `json:"created_at"`
	GroupID          string      `json:"group_id"`
	RecurringID      *string     `json:"recurring_id"`
	Name             string      `json:"name"`
	Description      *string     `json:"description"`
	Currency         string      `json:"currency"`
	PayerID          string      `json:"payer_id"`
	PayerName        string      `json:"payer_name"`
	Amount           int64       `json:"amount"`
	BeneficiariesIds interface{} `json:"beneficiaries_ids"`
}

func (q *Queries) GetGroupExpenses(ctx context.Context, groupID string) ([]GetGroupExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupExpenses, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupExpensesRow
	for rows.Next() {
		var i GetGroupExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.GroupID,
			&i.RecurringID,
			&i.Name,
			&i.Description,
			&i.Currency,
			&i.PayerID,
			&i.PayerName,
			&i.Amount,
			&i.BeneficiariesIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTotalSpending = `-- name: GetGroupTotalSpending :many
SELECT
  e.currency,
  CAST(SUM(p.amount) AS INTEGER) as total_amount
FROM expenses e
JOIN expense_payers p ON p.expense_id = e.id
WHERE e.group_id = ?1
GROUP BY e.currency
`

type GetGroupTotalSpendingRow struct {
	Currency    string `json:"currency"`
	TotalAmount int64  `json:"total_amount"`
}

func (q *Queries) GetGroupTotalSpending(ctx context.Context, groupID string) ([]GetGroupTotalSpendingRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupTotalSpending, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupTotalSpendingRow
	for rows.Next() {
		var i GetGroupTotalSpendingRow
		if err := rows.Scan(&i.Currency, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
