// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const addUserToGroup = `-- name: AddUserToGroup :one
INSERT INTO user_expense_groups
(
    user_id,
    group_id,
    weight,
    added_at
) VALUES (
    ?1, ?2, ?3, ?4
) RETURNING user_id, group_id, added_at, weight
`

type AddUserToGroupParams struct {
	UserID  string
	GroupID string
	Weight  float64
	AddedAt overrides.TextTime
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (UserExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, addUserToGroup,
		arg.UserID,
		arg.GroupID,
		arg.Weight,
		arg.AddedAt,
	)
	var i UserExpenseGroup
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.AddedAt,
		&i.Weight,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO expense_groups
(
    id,
    created_by,
    created_at,
    description,
    default_currency,
    name
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6
) RETURNING id, created_at, created_by, name, default_currency, description
`

type CreateGroupParams struct {
	ID              string
	CreatedBy       string
	CreatedAt       overrides.TextTime
	Description     *string
	DefaultCurrency string
	Name            string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.Description,
		arg.DefaultCurrency,
		arg.Name,
	)
	var i ExpenseGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Name,
		&i.DefaultCurrency,
		&i.Description,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM expense_groups
WHERE id = ?1
`

func (q *Queries) DeleteGroup(ctx context.Context, groupID string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, groupID)
	return err
}

const getGroupById = `-- name: GetGroupById :one
SELECT id, created_at, created_by, name, default_currency, description
FROM expense_groups
WHERE id = ?1
`

func (q *Queries) GetGroupById(ctx context.Context, groupID string) (ExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, groupID)
	var i ExpenseGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Name,
		&i.DefaultCurrency,
		&i.Description,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT
  ueg.user_id,
  ueg.weight,
  u.username as user_name
FROM user_expense_groups ueg
JOIN users u ON u.id = ueg.user_id
WHERE ueg.group_id = ?1
`

type GetGroupMembersRow struct {
	UserID   string
	Weight   float64
	UserName string
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID string) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.Weight, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByUserId = `-- name: GetGroupsByUserId :many
SELECT id, created_at, created_by, name, default_currency, description, user_id, group_id, added_at, weight
FROM
  expense_groups g
  LEFT JOIN user_expense_groups u ON u.group_id = g.id
WHERE u.user_id = ?1
`

type GetGroupsByUserIdRow struct {
	ID              string
	CreatedAt       overrides.TextTime
	CreatedBy       string
	Name            string
	DefaultCurrency string
	Description     *string
	UserID          *string
	GroupID         *string
	AddedAt         overrides.TextTime
	Weight          *float64
}

func (q *Queries) GetGroupsByUserId(ctx context.Context, userID string) ([]GetGroupsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByUserIdRow
	for rows.Next() {
		var i GetGroupsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Name,
			&i.DefaultCurrency,
			&i.Description,
			&i.UserID,
			&i.GroupID,
			&i.AddedAt,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInGroup = `-- name: IsUserInGroup :one
SELECT EXISTS(
    SELECT 1 FROM user_expense_groups
    WHERE user_id = ?1 AND group_id = ?2
) as is_member
`

type IsUserInGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUserInGroup, arg.UserID, arg.GroupID)
	var is_member int64
	err := row.Scan(&is_member)
	return is_member, err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
;

DELETE FROM user_expense_groups
WHERE user_id = ?1 AND group_id = ?2
`

type RemoveUserFromGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
;

UPDATE expense_groups SET name = ?1, description = ?2, default_currency = ?3
WHERE id = ?4
RETURNING id, created_at, created_by, name, default_currency, description
`

type UpdateGroupParams struct {
	Name            string
	Description     *string
	DefaultCurrency string
	ID              string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (ExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.DefaultCurrency,
		arg.ID,
	)
	var i ExpenseGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Name,
		&i.DefaultCurrency,
		&i.Description,
	)
	return i, err
}

const updateUserWeight = `-- name: UpdateUserWeight :exec
UPDATE user_expense_groups
SET weight = ?1
WHERE user_id = ?2 AND group_id = ?3
`

type UpdateUserWeightParams struct {
	Weight  float64
	UserID  string
	GroupID string
}

func (q *Queries) UpdateUserWeight(ctx context.Context, arg UpdateUserWeightParams) error {
	_, err := q.db.ExecContext(ctx, updateUserWeight, arg.Weight, arg.UserID, arg.GroupID)
	return err
}
