// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"
	"time"
)

const addUserToGroup = `-- name: AddUserToGroup :one
INSERT INTO user_expense_groups
(
    user_id,
    group_id,
    weight
) VALUES (
    ?, ?, ?
) RETURNING user_id, group_id, added_at, weight
`

type AddUserToGroupParams struct {
	UserID  string  `json:"user_id"`
	GroupID string  `json:"group_id"`
	Weight  float64 `json:"weight"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (UserExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, addUserToGroup, arg.UserID, arg.GroupID, arg.Weight)
	var i UserExpenseGroup
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.AddedAt,
		&i.Weight,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO expense_groups
(
    id,
    created_by,
    description,
    default_currency,
    name
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, created_at, created_by, name, default_currency, description
`

type CreateGroupParams struct {
	ID              string  `json:"id"`
	CreatedBy       string  `json:"created_by"`
	Description     *string `json:"description"`
	DefaultCurrency string  `json:"default_currency"`
	Name            string  `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.CreatedBy,
		arg.Description,
		arg.DefaultCurrency,
		arg.Name,
	)
	var i ExpenseGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Name,
		&i.DefaultCurrency,
		&i.Description,
	)
	return i, err
}

const getGroupById = `-- name: GetGroupById :one
SELECT id, created_at, created_by, name, default_currency, description
FROM expense_groups
WHERE id = ?1
`

func (q *Queries) GetGroupById(ctx context.Context, groupID string) (ExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, groupID)
	var i ExpenseGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Name,
		&i.DefaultCurrency,
		&i.Description,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT
  ueg.user_id,
  ueg.weight,
  u.username as user_name
FROM user_expense_groups ueg
JOIN users u ON u.id = ueg.user_id
WHERE ueg.group_id = ?1
`

type GetGroupMembersRow struct {
	UserID   string  `json:"user_id"`
	Weight   float64 `json:"weight"`
	UserName string  `json:"user_name"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID string) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.Weight, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByUserId = `-- name: GetGroupsByUserId :many
SELECT id, created_at, created_by, name, default_currency, description, user_id, group_id, added_at, weight
FROM 
  expense_groups g
  LEFT JOIN user_expense_groups u ON u.group_id = g.id
WHERE u.user_id = ?
`

type GetGroupsByUserIdRow struct {
	ID              string     `json:"id"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       string     `json:"created_by"`
	Name            string     `json:"name"`
	DefaultCurrency string     `json:"default_currency"`
	Description     *string    `json:"description"`
	UserID          *string    `json:"user_id"`
	GroupID         *string    `json:"group_id"`
	AddedAt         *time.Time `json:"added_at"`
	Weight          *float64   `json:"weight"`
}

func (q *Queries) GetGroupsByUserId(ctx context.Context, userID string) ([]GetGroupsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByUserIdRow
	for rows.Next() {
		var i GetGroupsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Name,
			&i.DefaultCurrency,
			&i.Description,
			&i.UserID,
			&i.GroupID,
			&i.AddedAt,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
;

DELETE FROM user_expense_groups
WHERE user_id = ? AND group_id = ?
`

type RemoveUserFromGroupParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
;

UPDATE expense_groups SET name = ?, description = ?
WHERE id = ?
RETURNING id, created_at, created_by, name, default_currency, description
`

type UpdateGroupParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (ExpenseGroup, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.Name, arg.Description, arg.ID)
	var i ExpenseGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Name,
		&i.DefaultCurrency,
		&i.Description,
	)
	return i, err
}
