// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"pennywise/db/overrides"
)

type Expense struct {
	ID          string
	CreatedAt   overrides.TextTime
	Date        overrides.TextTime
	GroupID     string
	RecurringID *string
	Name        string
	Description *string
	Currency    string
}

type ExpenseBeneficiary struct {
	ID        string
	ExpenseID string
	UserID    string
}

type ExpenseGroup struct {
	ID              string
	CreatedAt       overrides.TextTime
	CreatedBy       string
	Name            string
	DefaultCurrency string
	Description     *string
}

type ExpensePayer struct {
	ID        string
	ExpenseID string
	UserID    string
	Amount    int64
}

type RecurringExpense struct {
	ID             string
	CreatedAt      overrides.TextTime
	GroupID        string
	Name           string
	Description    *string
	Frequency      string
	StartDate      overrides.TextTime
	NextOccurrence overrides.TextTime
}

type Session struct {
	ID        string
	Token     string
	UserID    string
	CreatedAt overrides.TextTime
	UpdatedAt overrides.TextTime
	ExpiredAt overrides.TextTime
}

type Transfer struct {
	ID         string
	GroupID    string
	SenderID   string
	ReceiverID string
	Amount     int64
	Currency   string
	CreatedAt  overrides.TextTime
	Date       overrides.TextTime
}

type User struct {
	ID              string
	Email           string
	Username        string
	PasswordHash    *string
	CreatedAt       overrides.TextTime
	Role            int64
	ExpenseGroupIds *int64
}

type UserExpenseGroup struct {
	UserID  string
	GroupID string
	AddedAt overrides.TextTime
	Weight  float64
}
