// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"pennywise/db/overrides"
)

type Expense struct {
	ID          string
	CreatedAt   overrides.TextTime
	Date        overrides.TextTime
	GroupID     string
	RecurringID *string
	Name        string
	Description *string
	Currency    string
}

type ExpenseBeneficiary struct {
	ID        string
	ExpenseID string
	UserID    string
}

type ExpenseGroup struct {
	ID              string
	CreatedAt       overrides.TextTime
	CreatedBy       string
	Name            string
	DefaultCurrency string
	Description     *string
	ImageData       []byte
	ImageMimeType   *string
	ImageUpdatedAt  overrides.NullTextTime
}

type ExpensePayer struct {
	ID        string
	ExpenseID string
	UserID    string
	Amount    int64
}

type GroupCurrency struct {
	GroupID  string
	Currency string
}

type RecurringExpense struct {
	ID             string
	CreatedAt      overrides.TextTime
	GroupID        string
	Name           string
	Description    *string
	Frequency      string
	StartDate      overrides.TextTime
	NextOccurrence overrides.TextTime
	PayerID        *string
	Amount         *int64
	Currency       *string
}

type Session struct {
	ID        string
	Token     string
	UserID    string
	CreatedAt overrides.TextTime
	UpdatedAt overrides.TextTime
	ExpiredAt overrides.TextTime
}

type Transfer struct {
	ID         string
	GroupID    string
	SenderID   string
	ReceiverID string
	Amount     int64
	Currency   string
	CreatedAt  overrides.TextTime
	Date       overrides.TextTime
}

type User struct {
	ID              string
	Email           string
	Username        string
	PasswordHash    *string
	CreatedAt       overrides.TextTime
	Role            int64
	AvatarData      []byte
	AvatarMimeType  *string
	AvatarUpdatedAt overrides.NullTextTime
}

type UserExpenseGroup struct {
	UserID  string
	GroupID string
	AddedAt overrides.TextTime
	Weight  float64
}
