// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Expense struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Date        time.Time `json:"date"`
	GroupID     string    `json:"group_id"`
	RecurringID *string   `json:"recurring_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Currency    string    `json:"currency"`
}

type ExpenseBeneficiary struct {
	ID        string `json:"id"`
	ExpenseID string `json:"expense_id"`
	UserID    string `json:"user_id"`
}

type ExpenseGroup struct {
	ID              string    `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
	CreatedBy       string    `json:"created_by"`
	Name            string    `json:"name"`
	DefaultCurrency string    `json:"default_currency"`
	Description     *string   `json:"description"`
}

type ExpensePayer struct {
	ID        string `json:"id"`
	ExpenseID string `json:"expense_id"`
	UserID    string `json:"user_id"`
	Amount    int64  `json:"amount"`
}

type RecurringExpense struct {
	ID             string    `json:"id"`
	CreatedAt      time.Time `json:"created_at"`
	GroupID        string    `json:"group_id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	Frequency      string    `json:"frequency"`
	StartDate      time.Time `json:"start_date"`
	NextOccurrence time.Time `json:"next_occurrence"`
}

type Session struct {
	ID        string    `json:"id"`
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiredAt time.Time `json:"expired_at"`
}

type Transfer struct {
	ID         string    `json:"id"`
	GroupID    string    `json:"group_id"`
	SenderID   string    `json:"sender_id"`
	ReceiverID string    `json:"receiver_id"`
	Amount     int64     `json:"amount"`
	Currency   string    `json:"currency"`
	CreatedAt  time.Time `json:"created_at"`
	Date       time.Time `json:"date"`
}

type User struct {
	ID              string    `json:"id"`
	Email           string    `json:"email"`
	Username        string    `json:"username"`
	PasswordHash    *string   `json:"-"`
	CreatedAt       time.Time `json:"created_at"`
	Role            int64     `json:"role"`
	ExpenseGroupIds *int64    `json:"expense_group_ids"`
}

type UserExpenseGroup struct {
	UserID  string    `json:"user_id"`
	GroupID string    `json:"group_id"`
	AddedAt time.Time `json:"added_at"`
	Weight  float64   `json:"weight"`
}
