// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_expenses.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (
    id,
    created_at,
    group_id,
    name,
    description,
    frequency,
    start_date,
    next_occurrence,
    payer_id,
    amount,
    currency
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11
)
RETURNING id, created_at, group_id, name, description, frequency, start_date, next_occurrence, payer_id, amount, currency
`

type CreateRecurringExpenseParams struct {
	ID             string
	CreatedAt      overrides.TextTime
	GroupID        string
	Name           string
	Description    *string
	Frequency      string
	StartDate      overrides.TextTime
	NextOccurrence overrides.TextTime
	PayerID        *string
	Amount         *int64
	Currency       *string
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, createRecurringExpense,
		arg.ID,
		arg.CreatedAt,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.Frequency,
		arg.StartDate,
		arg.NextOccurrence,
		arg.PayerID,
		arg.Amount,
		arg.Currency,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.NextOccurrence,
		&i.PayerID,
		&i.Amount,
		&i.Currency,
	)
	return i, err
}

const deleteRecurringExpense = `-- name: DeleteRecurringExpense :exec
DELETE FROM recurring_expenses
WHERE id = ?1
`

func (q *Queries) DeleteRecurringExpense(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecurringExpense, id)
	return err
}

const getDueRecurringExpenses = `-- name: GetDueRecurringExpenses :many
SELECT
    r.id, r.created_at, r.group_id, r.name, r.description, r.frequency, r.start_date, r.next_occurrence, r.payer_id, r.amount, r.currency,
    u.username as payer_name
FROM recurring_expenses r
LEFT JOIN users u ON r.payer_id = u.id
WHERE r.group_id = ?1
  AND date(r.next_occurrence) <= date('now')
ORDER BY r.next_occurrence ASC
`

type GetDueRecurringExpensesRow struct {
	ID             string
	CreatedAt      overrides.TextTime
	GroupID        string
	Name           string
	Description    *string
	Frequency      string
	StartDate      overrides.TextTime
	NextOccurrence overrides.TextTime
	PayerID        *string
	Amount         *int64
	Currency       *string
	PayerName      *string
}

func (q *Queries) GetDueRecurringExpenses(ctx context.Context, groupID string) ([]GetDueRecurringExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDueRecurringExpenses, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueRecurringExpensesRow
	for rows.Next() {
		var i GetDueRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.Frequency,
			&i.StartDate,
			&i.NextOccurrence,
			&i.PayerID,
			&i.Amount,
			&i.Currency,
			&i.PayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupRecurringExpenses = `-- name: GetGroupRecurringExpenses :many
SELECT
    r.id, r.created_at, r.group_id, r.name, r.description, r.frequency, r.start_date, r.next_occurrence, r.payer_id, r.amount, r.currency,
    u.username as payer_name
FROM recurring_expenses r
LEFT JOIN users u ON r.payer_id = u.id
WHERE r.group_id = ?1
ORDER BY r.next_occurrence ASC
`

type GetGroupRecurringExpensesRow struct {
	ID             string
	CreatedAt      overrides.TextTime
	GroupID        string
	Name           string
	Description    *string
	Frequency      string
	StartDate      overrides.TextTime
	NextOccurrence overrides.TextTime
	PayerID        *string
	Amount         *int64
	Currency       *string
	PayerName      *string
}

func (q *Queries) GetGroupRecurringExpenses(ctx context.Context, groupID string) ([]GetGroupRecurringExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupRecurringExpenses, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupRecurringExpensesRow
	for rows.Next() {
		var i GetGroupRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.Frequency,
			&i.StartDate,
			&i.NextOccurrence,
			&i.PayerID,
			&i.Amount,
			&i.Currency,
			&i.PayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecurringExpense = `-- name: GetRecurringExpense :one
SELECT
    r.id, r.created_at, r.group_id, r.name, r.description, r.frequency, r.start_date, r.next_occurrence, r.payer_id, r.amount, r.currency,
    u.username as payer_name
FROM recurring_expenses r
LEFT JOIN users u ON r.payer_id = u.id
WHERE r.id = ?1
`

type GetRecurringExpenseRow struct {
	ID             string
	CreatedAt      overrides.TextTime
	GroupID        string
	Name           string
	Description    *string
	Frequency      string
	StartDate      overrides.TextTime
	NextOccurrence overrides.TextTime
	PayerID        *string
	Amount         *int64
	Currency       *string
	PayerName      *string
}

func (q *Queries) GetRecurringExpense(ctx context.Context, id string) (GetRecurringExpenseRow, error) {
	row := q.db.QueryRowContext(ctx, getRecurringExpense, id)
	var i GetRecurringExpenseRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.NextOccurrence,
		&i.PayerID,
		&i.Amount,
		&i.Currency,
		&i.PayerName,
	)
	return i, err
}

const updateNextOccurrence = `-- name: UpdateNextOccurrence :exec
UPDATE recurring_expenses
SET next_occurrence = ?1
WHERE id = ?2
`

type UpdateNextOccurrenceParams struct {
	NextOccurrence overrides.TextTime
	ID             string
}

func (q *Queries) UpdateNextOccurrence(ctx context.Context, arg UpdateNextOccurrenceParams) error {
	_, err := q.db.ExecContext(ctx, updateNextOccurrence, arg.NextOccurrence, arg.ID)
	return err
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses
SET
    name = ?1,
    description = ?2,
    frequency = ?3,
    payer_id = ?4,
    amount = ?5,
    currency = ?6
WHERE id = ?7
RETURNING id, created_at, group_id, name, description, frequency, start_date, next_occurrence, payer_id, amount, currency
`

type UpdateRecurringExpenseParams struct {
	Name        string
	Description *string
	Frequency   string
	PayerID     *string
	Amount      *int64
	Currency    *string
	ID          string
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, updateRecurringExpense,
		arg.Name,
		arg.Description,
		arg.Frequency,
		arg.PayerID,
		arg.Amount,
		arg.Currency,
		arg.ID,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.NextOccurrence,
		&i.PayerID,
		&i.Amount,
		&i.Currency,
	)
	return i, err
}
