// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions
(
    id,
    token,
    user_id,
    created_at,
    updated_at,
    expired_at
) VALUES (
    ?, ?, ?, ?, ?, ?
) RETURNING id, token, user_id, created_at, updated_at, expired_at
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiredAt time.Time `json:"expired_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiredAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, token, user_id, created_at, updated_at, expired_at FROM sessions WHERE token = ? LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByHash, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
;

SELECT id, token, user_id, created_at, updated_at, expired_at FROM sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionById(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getSessionByUserId = `-- name: GetSessionByUserId :one
SELECT id, token, user_id, created_at, updated_at, expired_at FROM sessions WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetSessionByUserId(ctx context.Context, userID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserId, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions SET token = ?, updated_at = ?, expired_at = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	Token     string    `json:"token"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiredAt time.Time `json:"expired_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.Token,
		arg.UpdatedAt,
		arg.ExpiredAt,
		arg.ID,
	)
	return err
}
