// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers
(
    id,
    created_at,
    group_id,
    sender_id,
    receiver_id,
    amount,
    currency,
    date
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
) RETURNING id, group_id, sender_id, receiver_id, amount, currency, created_at, date
`

type CreateTransferParams struct {
	ID         string
	CreatedAt  overrides.TextTime
	GroupID    string
	SenderID   string
	ReceiverID string
	Amount     int64
	Currency   string
	Date       overrides.TextTime
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.ID,
		arg.CreatedAt,
		arg.GroupID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Amount,
		arg.Currency,
		arg.Date,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Amount,
		&i.Currency,
		&i.CreatedAt,
		&i.Date,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = ?1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, id)
	return err
}

const getGroupTransfers = `-- name: GetGroupTransfers :many
SELECT
    t.id, t.group_id, t.sender_id, t.receiver_id, t.amount, t.currency, t.created_at, t.date,
    s.username as sender_name,
    r.username as receiver_name
FROM transfers t
JOIN users s ON s.id = t.sender_id
JOIN users r ON r.id = t.receiver_id
WHERE t.group_id = ?1
ORDER BY t.created_at DESC
`

type GetGroupTransfersRow struct {
	ID           string
	GroupID      string
	SenderID     string
	ReceiverID   string
	Amount       int64
	Currency     string
	CreatedAt    overrides.TextTime
	Date         overrides.TextTime
	SenderName   string
	ReceiverName string
}

func (q *Queries) GetGroupTransfers(ctx context.Context, groupID string) ([]GetGroupTransfersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupTransfers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupTransfersRow
	for rows.Next() {
		var i GetGroupTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Amount,
			&i.Currency,
			&i.CreatedAt,
			&i.Date,
			&i.SenderName,
			&i.ReceiverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTransfersForBalance = `-- name: GetGroupTransfersForBalance :many
SELECT
    sender_id,
    receiver_id,
    amount,
    currency
FROM transfers
WHERE group_id = ?1
`

type GetGroupTransfersForBalanceRow struct {
	SenderID   string
	ReceiverID string
	Amount     int64
	Currency   string
}

func (q *Queries) GetGroupTransfersForBalance(ctx context.Context, groupID string) ([]GetGroupTransfersForBalanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupTransfersForBalance, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupTransfersForBalanceRow
	for rows.Next() {
		var i GetGroupTransfersForBalanceRow
		if err := rows.Scan(
			&i.SenderID,
			&i.ReceiverID,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferById = `-- name: GetTransferById :one
SELECT id, group_id, sender_id, receiver_id, amount, currency, created_at, date FROM transfers WHERE id = ?1
`

func (q *Queries) GetTransferById(ctx context.Context, id string) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferById, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Amount,
		&i.Currency,
		&i.CreatedAt,
		&i.Date,
	)
	return i, err
}

const updateTransfer = `-- name: UpdateTransfer :one
UPDATE transfers
SET
    sender_id = ?1,
    receiver_id = ?2,
    amount = ?3,
    currency = ?4,
    date = ?5
WHERE id = ?6
RETURNING id, group_id, sender_id, receiver_id, amount, currency, created_at, date
`

type UpdateTransferParams struct {
	SenderID   string
	ReceiverID string
	Amount     int64
	Currency   string
	Date       overrides.TextTime
	ID         string
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, updateTransfer,
		arg.SenderID,
		arg.ReceiverID,
		arg.Amount,
		arg.Currency,
		arg.Date,
		arg.ID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Amount,
		&i.Currency,
		&i.CreatedAt,
		&i.Date,
	)
	return i, err
}
