// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package database

import (
	"context"
	"time"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers
(
    id,
    group_id,
    sender_id,
    receiver_id,
    amount,
    currency,
    created_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
) RETURNING id, group_id, sender_id, receiver_id, amount, currency, created_at
`

type CreateTransferParams struct {
	ID         string    `json:"id"`
	GroupID    string    `json:"group_id"`
	SenderID   string    `json:"sender_id"`
	ReceiverID string    `json:"receiver_id"`
	Amount     int64     `json:"amount"`
	Currency   string    `json:"currency"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.ID,
		arg.GroupID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Amount,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Amount,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = ?1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, id)
	return err
}

const getGroupTransfers = `-- name: GetGroupTransfers :many
SELECT
    t.id, t.group_id, t.sender_id, t.receiver_id, t.amount, t.currency, t.created_at,
    s.username as sender_name,
    r.username as receiver_name
FROM transfers t
JOIN users s ON s.id = t.sender_id
JOIN users r ON r.id = t.receiver_id
WHERE t.group_id = ?1
ORDER BY t.created_at DESC
`

type GetGroupTransfersRow struct {
	ID           string    `json:"id"`
	GroupID      string    `json:"group_id"`
	SenderID     string    `json:"sender_id"`
	ReceiverID   string    `json:"receiver_id"`
	Amount       int64     `json:"amount"`
	Currency     string    `json:"currency"`
	CreatedAt    time.Time `json:"created_at"`
	SenderName   string    `json:"sender_name"`
	ReceiverName string    `json:"receiver_name"`
}

func (q *Queries) GetGroupTransfers(ctx context.Context, groupID string) ([]GetGroupTransfersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupTransfers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupTransfersRow
	for rows.Next() {
		var i GetGroupTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Amount,
			&i.Currency,
			&i.CreatedAt,
			&i.SenderName,
			&i.ReceiverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTransfersForBalance = `-- name: GetGroupTransfersForBalance :many
SELECT
    sender_id,
    receiver_id,
    amount,
    currency
FROM transfers
WHERE group_id = ?1
`

type GetGroupTransfersForBalanceRow struct {
	SenderID   string `json:"sender_id"`
	ReceiverID string `json:"receiver_id"`
	Amount     int64  `json:"amount"`
	Currency   string `json:"currency"`
}

func (q *Queries) GetGroupTransfersForBalance(ctx context.Context, groupID string) ([]GetGroupTransfersForBalanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupTransfersForBalance, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupTransfersForBalanceRow
	for rows.Next() {
		var i GetGroupTransfersForBalanceRow
		if err := rows.Scan(
			&i.SenderID,
			&i.ReceiverID,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferById = `-- name: GetTransferById :one
SELECT id, group_id, sender_id, receiver_id, amount, currency, created_at FROM transfers WHERE id = ?1
`

func (q *Queries) GetTransferById(ctx context.Context, id string) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferById, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Amount,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const isUserInGroup = `-- name: IsUserInGroup :one
SELECT EXISTS(
    SELECT 1 FROM user_expense_groups
    WHERE user_id = ?1 AND group_id = ?2
) as is_member
`

type IsUserInGroupParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUserInGroup, arg.UserID, arg.GroupID)
	var is_member int64
	err := row.Scan(&is_member)
	return is_member, err
}

const updateTransfer = `-- name: UpdateTransfer :one
UPDATE transfers
SET
    sender_id = ?1,
    receiver_id = ?2,
    amount = ?3,
    currency = ?4
WHERE id = ?5
RETURNING id, group_id, sender_id, receiver_id, amount, currency, created_at
`

type UpdateTransferParams struct {
	SenderID   string `json:"sender_id"`
	ReceiverID string `json:"receiver_id"`
	Amount     int64  `json:"amount"`
	Currency   string `json:"currency"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, updateTransfer,
		arg.SenderID,
		arg.ReceiverID,
		arg.Amount,
		arg.Currency,
		arg.ID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Amount,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
