// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(
    id,
    email,
    username,
    password_hash,
    created_at,
    role
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6
) RETURNING id, email, username, password_hash, created_at, role, expense_group_ids, avatar_data, avatar_mime_type, avatar_updated_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	Username     string
	PasswordHash *string
	CreatedAt    overrides.TextTime
	Role         int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.ExpenseGroupIds,
		&i.AvatarData,
		&i.AvatarMimeType,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT avatar_data, avatar_mime_type FROM users WHERE id = ?1 LIMIT 1
`

type GetUserAvatarRow struct {
	AvatarData     []byte
	AvatarMimeType *string
}

func (q *Queries) GetUserAvatar(ctx context.Context, id string) (GetUserAvatarRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatar, id)
	var i GetUserAvatarRow
	err := row.Scan(&i.AvatarData, &i.AvatarMimeType)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, created_at, role, expense_group_ids, avatar_data, avatar_mime_type, avatar_updated_at FROM users WHERE email = ?1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.ExpenseGroupIds,
		&i.AvatarData,
		&i.AvatarMimeType,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
;

SELECT id, email, username, role, avatar_updated_at FROM users WHERE id = ?1 LIMIT 1
`

type GetUserByIdRow struct {
	ID              string
	Email           string
	Username        string
	Role            int64
	AvatarUpdatedAt overrides.NullTextTime
}

func (q *Queries) GetUserById(ctx context.Context, id string) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, email FROM users
`

type GetUsersRow struct {
	ID       string
	Username string
	Email    string
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_data = ?1, avatar_mime_type = ?2, avatar_updated_at = ?3
WHERE id = ?4
`

type UpdateUserAvatarParams struct {
	AvatarData      []byte
	AvatarMimeType  *string
	AvatarUpdatedAt overrides.NullTextTime
	ID              string
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar,
		arg.AvatarData,
		arg.AvatarMimeType,
		arg.AvatarUpdatedAt,
		arg.ID,
	)
	return err
}
