// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"pennywise/db/overrides"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role = 1
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users
(
    id,
    email,
    username,
    password_hash,
    created_at,
    role
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6
) RETURNING id, email, username, password_hash, created_at, role, avatar_updated_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	Username     string
	PasswordHash *string
	CreatedAt    overrides.TextTime
	Role         int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, created_at, role, avatar_updated_at FROM users WHERE email = ?1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
;

SELECT id, email, username, role, avatar_updated_at FROM users WHERE id = ?1 LIMIT 1
`

type GetUserByIdRow struct {
	ID              string
	Email           string
	Username        string
	Role            int64
	AvatarUpdatedAt overrides.NullTextTime
}

func (q *Queries) GetUserById(ctx context.Context, id string) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, email, role FROM users
`

type GetUsersRow struct {
	ID       string
	Username string
	Email    string
	Role     int64
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUsersEmpty = `-- name: IsUsersEmpty :one
SELECT NOT EXISTS(SELECT 1 FROM users LIMIT 1)
`

func (q *Queries) IsUsersEmpty(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUsersEmpty)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_updated_at = ?1
WHERE id = ?2
`

type UpdateUserAvatarParams struct {
	AvatarUpdatedAt overrides.NullTextTime
	ID              string
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.AvatarUpdatedAt, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = ?1
WHERE id = ?2
RETURNING id, email, username, role
`

type UpdateUserRoleParams struct {
	Role int64
	ID   string
}

type UpdateUserRoleRow struct {
	ID       string
	Email    string
	Username string
	Role     int64
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.Role, arg.ID)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users
SET username = ?1
WHERE id = ?2
RETURNING id, email, username, role, avatar_updated_at
`

type UpdateUserUsernameParams struct {
	Username string
	ID       string
}

type UpdateUserUsernameRow struct {
	ID              string
	Email           string
	Username        string
	Role            int64
	AvatarUpdatedAt overrides.NullTextTime
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (UpdateUserUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserUsername, arg.Username, arg.ID)
	var i UpdateUserUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.AvatarUpdatedAt,
	)
	return i, err
}
