/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugErrorRouteImport } from './routes/debug-error'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PathlessLayoutSettingsRouteImport } from './routes/_pathlessLayout/settings'
import { Route as PathlessLayoutScanReceiptRouteImport } from './routes/_pathlessLayout/scan-receipt'
import { Route as PathlessLayoutDashboardRouteImport } from './routes/_pathlessLayout/dashboard'
import { Route as PathlessLayoutAdminRouteRouteImport } from './routes/_pathlessLayout/admin/route'
import { Route as PathlessLayoutAdminIndexRouteImport } from './routes/_pathlessLayout/admin/index'
import { Route as PathlessLayoutAdminMembersRouteImport } from './routes/_pathlessLayout/admin/members'
import { Route as PathlessLayoutAdminGroupsRouteImport } from './routes/_pathlessLayout/admin/groups'
import { Route as PathlessLayoutAdminCurrenciesRouteImport } from './routes/_pathlessLayout/admin/currencies'
import { Route as PathlessLayoutAdminAiRouteImport } from './routes/_pathlessLayout/admin/ai'
import { Route as PathlessLayoutGroupGroupIdRouteRouteImport } from './routes/_pathlessLayout/group/$groupId/route'
import { Route as PathlessLayoutGroupGroupIdIndexRouteImport } from './routes/_pathlessLayout/group/$groupId/index'
import { Route as PathlessLayoutGroupGroupIdStatsRouteImport } from './routes/_pathlessLayout/group/$groupId/stats'

const DebugErrorRoute = DebugErrorRouteImport.update({
  id: '/debug-error',
  path: '/debug-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutSettingsRoute = PathlessLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutScanReceiptRoute =
  PathlessLayoutScanReceiptRouteImport.update({
    id: '/scan-receipt',
    path: '/scan-receipt',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutDashboardRoute = PathlessLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutAdminRouteRoute =
  PathlessLayoutAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutAdminIndexRoute =
  PathlessLayoutAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)
const PathlessLayoutAdminMembersRoute =
  PathlessLayoutAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)
const PathlessLayoutAdminGroupsRoute =
  PathlessLayoutAdminGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)
const PathlessLayoutAdminCurrenciesRoute =
  PathlessLayoutAdminCurrenciesRouteImport.update({
    id: '/currencies',
    path: '/currencies',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)
const PathlessLayoutAdminAiRoute = PathlessLayoutAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PathlessLayoutAdminRouteRoute,
} as any)
const PathlessLayoutGroupGroupIdRouteRoute =
  PathlessLayoutGroupGroupIdRouteRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutGroupGroupIdIndexRoute =
  PathlessLayoutGroupGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PathlessLayoutGroupGroupIdRouteRoute,
  } as any)
const PathlessLayoutGroupGroupIdStatsRoute =
  PathlessLayoutGroupGroupIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => PathlessLayoutGroupGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug-error': typeof DebugErrorRoute
  '/admin': typeof PathlessLayoutAdminRouteRouteWithChildren
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/scan-receipt': typeof PathlessLayoutScanReceiptRoute
  '/settings': typeof PathlessLayoutSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/group/$groupId': typeof PathlessLayoutGroupGroupIdRouteRouteWithChildren
  '/admin/ai': typeof PathlessLayoutAdminAiRoute
  '/admin/currencies': typeof PathlessLayoutAdminCurrenciesRoute
  '/admin/groups': typeof PathlessLayoutAdminGroupsRoute
  '/admin/members': typeof PathlessLayoutAdminMembersRoute
  '/admin/': typeof PathlessLayoutAdminIndexRoute
  '/group/$groupId/stats': typeof PathlessLayoutGroupGroupIdStatsRoute
  '/group/$groupId/': typeof PathlessLayoutGroupGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug-error': typeof DebugErrorRoute
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/scan-receipt': typeof PathlessLayoutScanReceiptRoute
  '/settings': typeof PathlessLayoutSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/ai': typeof PathlessLayoutAdminAiRoute
  '/admin/currencies': typeof PathlessLayoutAdminCurrenciesRoute
  '/admin/groups': typeof PathlessLayoutAdminGroupsRoute
  '/admin/members': typeof PathlessLayoutAdminMembersRoute
  '/admin': typeof PathlessLayoutAdminIndexRoute
  '/group/$groupId/stats': typeof PathlessLayoutGroupGroupIdStatsRoute
  '/group/$groupId': typeof PathlessLayoutGroupGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/debug-error': typeof DebugErrorRoute
  '/_pathlessLayout/admin': typeof PathlessLayoutAdminRouteRouteWithChildren
  '/_pathlessLayout/dashboard': typeof PathlessLayoutDashboardRoute
  '/_pathlessLayout/scan-receipt': typeof PathlessLayoutScanReceiptRoute
  '/_pathlessLayout/settings': typeof PathlessLayoutSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_pathlessLayout/group/$groupId': typeof PathlessLayoutGroupGroupIdRouteRouteWithChildren
  '/_pathlessLayout/admin/ai': typeof PathlessLayoutAdminAiRoute
  '/_pathlessLayout/admin/currencies': typeof PathlessLayoutAdminCurrenciesRoute
  '/_pathlessLayout/admin/groups': typeof PathlessLayoutAdminGroupsRoute
  '/_pathlessLayout/admin/members': typeof PathlessLayoutAdminMembersRoute
  '/_pathlessLayout/admin/': typeof PathlessLayoutAdminIndexRoute
  '/_pathlessLayout/group/$groupId/stats': typeof PathlessLayoutGroupGroupIdStatsRoute
  '/_pathlessLayout/group/$groupId/': typeof PathlessLayoutGroupGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug-error'
    | '/admin'
    | '/dashboard'
    | '/scan-receipt'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/group/$groupId'
    | '/admin/ai'
    | '/admin/currencies'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/'
    | '/group/$groupId/stats'
    | '/group/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug-error'
    | '/dashboard'
    | '/scan-receipt'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/admin/ai'
    | '/admin/currencies'
    | '/admin/groups'
    | '/admin/members'
    | '/admin'
    | '/group/$groupId/stats'
    | '/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/debug-error'
    | '/_pathlessLayout/admin'
    | '/_pathlessLayout/dashboard'
    | '/_pathlessLayout/scan-receipt'
    | '/_pathlessLayout/settings'
    | '/auth/login'
    | '/auth/register'
    | '/_pathlessLayout/group/$groupId'
    | '/_pathlessLayout/admin/ai'
    | '/_pathlessLayout/admin/currencies'
    | '/_pathlessLayout/admin/groups'
    | '/_pathlessLayout/admin/members'
    | '/_pathlessLayout/admin/'
    | '/_pathlessLayout/group/$groupId/stats'
    | '/_pathlessLayout/group/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  DebugErrorRoute: typeof DebugErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug-error': {
      id: '/debug-error'
      path: '/debug-error'
      fullPath: '/debug-error'
      preLoaderRoute: typeof DebugErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/settings': {
      id: '/_pathlessLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PathlessLayoutSettingsRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/scan-receipt': {
      id: '/_pathlessLayout/scan-receipt'
      path: '/scan-receipt'
      fullPath: '/scan-receipt'
      preLoaderRoute: typeof PathlessLayoutScanReceiptRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/dashboard': {
      id: '/_pathlessLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathlessLayoutDashboardRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/admin': {
      id: '/_pathlessLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PathlessLayoutAdminRouteRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/admin/': {
      id: '/_pathlessLayout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof PathlessLayoutAdminIndexRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/members': {
      id: '/_pathlessLayout/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof PathlessLayoutAdminMembersRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/groups': {
      id: '/_pathlessLayout/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof PathlessLayoutAdminGroupsRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/currencies': {
      id: '/_pathlessLayout/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof PathlessLayoutAdminCurrenciesRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/ai': {
      id: '/_pathlessLayout/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof PathlessLayoutAdminAiRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/group/$groupId': {
      id: '/_pathlessLayout/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof PathlessLayoutGroupGroupIdRouteRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/group/$groupId/': {
      id: '/_pathlessLayout/group/$groupId/'
      path: '/'
      fullPath: '/group/$groupId/'
      preLoaderRoute: typeof PathlessLayoutGroupGroupIdIndexRouteImport
      parentRoute: typeof PathlessLayoutGroupGroupIdRouteRoute
    }
    '/_pathlessLayout/group/$groupId/stats': {
      id: '/_pathlessLayout/group/$groupId/stats'
      path: '/stats'
      fullPath: '/group/$groupId/stats'
      preLoaderRoute: typeof PathlessLayoutGroupGroupIdStatsRouteImport
      parentRoute: typeof PathlessLayoutGroupGroupIdRouteRoute
    }
  }
}

interface PathlessLayoutAdminRouteRouteChildren {
  PathlessLayoutAdminAiRoute: typeof PathlessLayoutAdminAiRoute
  PathlessLayoutAdminCurrenciesRoute: typeof PathlessLayoutAdminCurrenciesRoute
  PathlessLayoutAdminGroupsRoute: typeof PathlessLayoutAdminGroupsRoute
  PathlessLayoutAdminMembersRoute: typeof PathlessLayoutAdminMembersRoute
  PathlessLayoutAdminIndexRoute: typeof PathlessLayoutAdminIndexRoute
}

const PathlessLayoutAdminRouteRouteChildren: PathlessLayoutAdminRouteRouteChildren =
  {
    PathlessLayoutAdminAiRoute: PathlessLayoutAdminAiRoute,
    PathlessLayoutAdminCurrenciesRoute: PathlessLayoutAdminCurrenciesRoute,
    PathlessLayoutAdminGroupsRoute: PathlessLayoutAdminGroupsRoute,
    PathlessLayoutAdminMembersRoute: PathlessLayoutAdminMembersRoute,
    PathlessLayoutAdminIndexRoute: PathlessLayoutAdminIndexRoute,
  }

const PathlessLayoutAdminRouteRouteWithChildren =
  PathlessLayoutAdminRouteRoute._addFileChildren(
    PathlessLayoutAdminRouteRouteChildren,
  )

interface PathlessLayoutGroupGroupIdRouteRouteChildren {
  PathlessLayoutGroupGroupIdStatsRoute: typeof PathlessLayoutGroupGroupIdStatsRoute
  PathlessLayoutGroupGroupIdIndexRoute: typeof PathlessLayoutGroupGroupIdIndexRoute
}

const PathlessLayoutGroupGroupIdRouteRouteChildren: PathlessLayoutGroupGroupIdRouteRouteChildren =
  {
    PathlessLayoutGroupGroupIdStatsRoute: PathlessLayoutGroupGroupIdStatsRoute,
    PathlessLayoutGroupGroupIdIndexRoute: PathlessLayoutGroupGroupIdIndexRoute,
  }

const PathlessLayoutGroupGroupIdRouteRouteWithChildren =
  PathlessLayoutGroupGroupIdRouteRoute._addFileChildren(
    PathlessLayoutGroupGroupIdRouteRouteChildren,
  )

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutAdminRouteRoute: typeof PathlessLayoutAdminRouteRouteWithChildren
  PathlessLayoutDashboardRoute: typeof PathlessLayoutDashboardRoute
  PathlessLayoutScanReceiptRoute: typeof PathlessLayoutScanReceiptRoute
  PathlessLayoutSettingsRoute: typeof PathlessLayoutSettingsRoute
  PathlessLayoutGroupGroupIdRouteRoute: typeof PathlessLayoutGroupGroupIdRouteRouteWithChildren
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutAdminRouteRoute: PathlessLayoutAdminRouteRouteWithChildren,
  PathlessLayoutDashboardRoute: PathlessLayoutDashboardRoute,
  PathlessLayoutScanReceiptRoute: PathlessLayoutScanReceiptRoute,
  PathlessLayoutSettingsRoute: PathlessLayoutSettingsRoute,
  PathlessLayoutGroupGroupIdRouteRoute:
    PathlessLayoutGroupGroupIdRouteRouteWithChildren,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  DebugErrorRoute: DebugErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
