/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PathlessLayoutSettingsRouteImport } from './routes/_pathlessLayout/settings'
import { Route as PathlessLayoutScanReceiptRouteImport } from './routes/_pathlessLayout/scan-receipt'
import { Route as PathlessLayoutDashboardRouteImport } from './routes/_pathlessLayout/dashboard'
import { Route as PathlessLayoutGroupGroupIdRouteImport } from './routes/_pathlessLayout/group/$groupId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutSettingsRoute = PathlessLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutScanReceiptRoute =
  PathlessLayoutScanReceiptRouteImport.update({
    id: '/scan-receipt',
    path: '/scan-receipt',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutDashboardRoute = PathlessLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutGroupGroupIdRoute =
  PathlessLayoutGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/scan-receipt': typeof PathlessLayoutScanReceiptRoute
  '/settings': typeof PathlessLayoutSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/group/$groupId': typeof PathlessLayoutGroupGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/scan-receipt': typeof PathlessLayoutScanReceiptRoute
  '/settings': typeof PathlessLayoutSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/group/$groupId': typeof PathlessLayoutGroupGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_pathlessLayout/dashboard': typeof PathlessLayoutDashboardRoute
  '/_pathlessLayout/scan-receipt': typeof PathlessLayoutScanReceiptRoute
  '/_pathlessLayout/settings': typeof PathlessLayoutSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_pathlessLayout/group/$groupId': typeof PathlessLayoutGroupGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/scan-receipt'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/scan-receipt'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/about'
    | '/_pathlessLayout/dashboard'
    | '/_pathlessLayout/scan-receipt'
    | '/_pathlessLayout/settings'
    | '/auth/login'
    | '/auth/register'
    | '/_pathlessLayout/group/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/settings': {
      id: '/_pathlessLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PathlessLayoutSettingsRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/scan-receipt': {
      id: '/_pathlessLayout/scan-receipt'
      path: '/scan-receipt'
      fullPath: '/scan-receipt'
      preLoaderRoute: typeof PathlessLayoutScanReceiptRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/dashboard': {
      id: '/_pathlessLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathlessLayoutDashboardRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/group/$groupId': {
      id: '/_pathlessLayout/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof PathlessLayoutGroupGroupIdRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutDashboardRoute: typeof PathlessLayoutDashboardRoute
  PathlessLayoutScanReceiptRoute: typeof PathlessLayoutScanReceiptRoute
  PathlessLayoutSettingsRoute: typeof PathlessLayoutSettingsRoute
  PathlessLayoutGroupGroupIdRoute: typeof PathlessLayoutGroupGroupIdRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutDashboardRoute: PathlessLayoutDashboardRoute,
  PathlessLayoutScanReceiptRoute: PathlessLayoutScanReceiptRoute,
  PathlessLayoutSettingsRoute: PathlessLayoutSettingsRoute,
  PathlessLayoutGroupGroupIdRoute: PathlessLayoutGroupGroupIdRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
